apiVersion: apps/v1
kind: Deployment
metadata:
  name: kavita
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kavita
  template:
    metadata:
      labels:
        app: kavita
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: kavita
        image: linuxserver/kavita:latest
        ports:
        - containerPort: 5000
        env:
        - name: TZ
          value: "America/Toronto"
        volumeMounts:
        - name: comics
          mountPath: /comics
          readOnly: true
        - name: data
          mountPath: /data
      volumes:
      - name: comics
        persistentVolumeClaim:
          claimName: pvc-nfs-comics
      - name: data
        persistentVolumeClaim:
          claimName: pvc-kavita-data
---
apiVersion: v1
kind: Service
metadata:
  name: kavita
  namespace: media
spec:
  selector:
    app: kavita
  ports:
  - port: 5000
    targetPort: 5000
  type: NodePort

