apiVersion: v1
kind: Namespace
metadata:
  name: foundryvtt
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: foundry-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 10.27.27.250
    path: /volume1/foundry
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foundry-pvc
  namespace: foundryvtt
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: nfs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foundry-vtt
  namespace: foundryvtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foundry-vtt
  template:
    metadata:
      labels:
        app: foundry-vtt
    spec:
      containers:
        - name: foundryvtt
          image: felddy/foundryvtt
          envFrom:
            - secretRef:
                name: foundry-auth             
          volumeMounts:
            - mountPath: /data
              name: foundry-data
      volumes:
        - name: foundry-data
          persistentVolumeClaim:
            claimName: foundry-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: foundry-service
  namespace: foundryvtt
spec:
  selector:
    app: foundry-vtt
  type: NodePort
  ports:
    - name: webui
      port: 30000
      targetPort: 30000
      nodePort: 32555
