parent:
  enabled: false

child:
  enabled: true
  replicas: 1

  configs:
    netdata:
      enabled: true
      data: |
        [global]
          bind to = 0.0.0.0
        [web]
          bind to = 0.0.0.0:19999
        [health]
          enabled = no
        [ml]
          enabled = no
        [db]
          mode = dbengine
          update every = 1

           # retention in seconds
          tier 0 = 600        # 10 minutes @ 1s resolution
          tier 1 = 86400      # 24 hours @ 1-minute resolution
          tier 2 = 604800  
  service:
    type: NodePort
    nodePort: 31000

  claimName: netdata-pvc

ingress:
  enabled: false

persistence:
  enabled: true
  size: 10Gi
  storageClass: local-path

