# dashy-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashy
  namespace: dashy
  labels:
    app: dashy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashy
  template:
    metadata:
      labels:
        app: dashy
    spec:
      containers:
        - name: dashy
          image: lissy93/dashy:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: dashy-data
              mountPath: /app/public/conf.yml
              subPath: conf.yml
      volumes:
        - name: dashy-data
          persistentVolumeClaim:
            claimName: dashy-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: dashy
  namespace: dashy
spec:
  selector:
    app: dashy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort

